export type GameMode = "learn" | "practice" | "test";
export type Subject = "English" | "Hindi" | "Telugu" | "Math" | "Science" | "Logic";

export interface GameInfo {
  id: string;
  title: string;
  desc: string;
  iconName: string;
  path: string;
  subject: Subject;
}

export const GAME_CATEGORIES: Record<GameMode, GameInfo[]> = {
  learn: [
    {
      id: "alphabet",
      title: "ABC Alphabet",
      desc: "Learn letters and sounds",
      iconName: "Type",
      path: "/alphabet",
      subject: "English",
    },
    {
      id: "learn_numbers",
      title: "Learn Numbers",
      desc: "Count 1, 2, 3 with fun objects",
      iconName: "Hash",
      path: "/learn_numbers",
      subject: "Math",
    },
    {
      id: "alphabet_hindi",
      title: "Hindi Letters",
      desc: "Varnamala with joy",
      iconName: "Languages",
      path: "/alphabet_hindi",
      subject: "Hindi",
    },
    {
      id: "sight_words",
      title: "Sight Words",
      desc: "Words like The, Is, And",
      iconName: "BookOpen",
      path: "/sight_words",
      subject: "English",
    },
    {
      id: "alphabet_telugu",
      title: "Telugu Letters",
      desc: "Learn Telugu Varnasala",
      iconName: "Languages",
      path: "/alphabet_telugu",
      subject: "Telugu",
    },
    {
      id: "weeks_english",
      title: "Weeks",
      desc: "Learn Sun, Mon, Tue...",
      iconName: "Calendar",
      path: "/weeks_english",
      subject: "English",
    },
    {
      id: "months_english",
      title: "Months",
      desc: "Jan, Feb, Mar...Dec",
      iconName: "CalendarDays",
      path: "/months_english",
      subject: "English",
    },
    {
      id: "weeks_telugu",
      title: "Weeks",
      desc: "Learn days in Telugu",
      iconName: "Calendar",
      path: "/weeks_telugu",
      subject: "Telugu",
    },
    {
      id: "shapes",
      title: "Shapes",
      desc: "Circles, squares & more!",
      iconName: "Shapes",
      path: "/shapes",
      subject: "Math",
    },
    {
      id: "body_parts",
      title: "Body Parts",
      desc: "Head, hands, legs & more",
      iconName: "HeartPulse",
      path: "/body_parts",
      subject: "Science",
    },
    {
      id: "sense_organs",
      title: "Sense Organs",
      desc: "Eyes, ears, nose, tongue, skin",
      iconName: "Eye",
      path: "/sense_organs",
      subject: "Science",
    },
    {
      id: "weeks_hindi",
      title: "Weeks",
      desc: "Learn days in Hindi",
      iconName: "Calendar",
      path: "/weeks_hindi",
      subject: "Hindi",
    },
    {
      id: "numbers_english_spelling",
      title: "Number Spelling",
      desc: "One, Two, Three...",
      iconName: "Hash",
      path: "/numbers_english_spelling",
      subject: "English",
    },
    {
      id: "numbers_hindi",
      title: "Numbers",
      desc: "1, 2, 3 - एक, दो, तीन",
      iconName: "Hash",
      path: "/numbers_hindi",
      subject: "Hindi",
    },
    {
      id: "numbers_telugu",
      title: "Numbers",
      desc: "1, 2, 3 - ఒకటి, రెండు",
      iconName: "Hash",
      path: "/numbers_telugu",
      subject: "Telugu",
    },
    {
      id: "months_telugu",
      title: "Months",
      desc: "January, February...",
      iconName: "CalendarDays",
      path: "/months_telugu",
      subject: "Telugu",
    },
    {
      id: "months_hindi",
      title: "Months",
      desc: "January, February...",
      iconName: "CalendarDays",
      path: "/months_hindi",
      subject: "Hindi",
    },
    {
      id: "place_values",
      title: "Place Values",
      desc: "Ones, Tens, Hundreds...",
      iconName: "Binary",
      path: "/place_values",
      subject: "Math",
    },
  ],
  practice: [
    {
      id: "missing_letters",
      title: "Missing Letters",
      desc: "Complete the words",
      iconName: "Search",
      path: "/missing_letters",
      subject: "English",
    },
    {
      id: "spelling",
      title: "Spelling Bee",
      desc: "Type the correct word",
      iconName: "Gamepad2",
      path: "/spelling",
      subject: "English",
    },
    {
      id: "math",
      title: "Math Magic",
      desc: "Fun addition/subtraction",
      iconName: "Calculator",
      path: "/counting",
      subject: "Math",
    },
    {
      id: "sudoku",
      title: "Kid Sudoku",
      desc: "Solve logic puzzles",
      iconName: "Grid3X3",
      path: "/sudoku",
      subject: "Math",
    },
    {
      id: "sorting",
      title: "Sorting Fun",
      desc: "Order numbers correctly",
      iconName: "ArrowUpDown",
      path: "/sorting_numbers",
      subject: "Math",
    },
    {
      id: "comparison",
      title: "Big or Small",
      desc: "Compare the values",
      iconName: "LayoutGrid",
      path: "/comparison",
      subject: "Math",
    },
  ],
  test: [
    {
      id: "math_addition",
      title: "Addition",
      desc: "Practice plus (+) sums",
      iconName: "Calculator",
      path: "/test/math_addition",
      subject: "Math",
    },
    {
      id: "math_subtraction",
      title: "Subtraction",
      desc: "Practice minus (-) sums",
      iconName: "Calculator",
      path: "/test/math_subtraction",
      subject: "Math",
    },
    {
      id: "math_multiplication",
      title: "Multiplication",
      desc: "Practice times (x) sums",
      iconName: "Calculator",
      path: "/test/math_multiplication",
      subject: "Math",
    },
    {
      id: "math_division",
      title: "Division",
      desc: "Practice divide (/) sums",
      iconName: "Calculator",
      path: "/test/math_division",
      subject: "Math",
    },
    {
      id: "math_sorting",
      title: "Sorting",
      desc: "Order numbers (Asc/Desc)",
      iconName: "ArrowUpDown",
      path: "/test/math_sorting",
      subject: "Math",
    },
    {
      id: "math_test",
      title: "Math Hero",
      desc: "Mix of + , - , x",
      iconName: "Trophy",
      path: "/test/math_test",
      subject: "Math",
    },
    {
      id: "english_missing_letters",
      title: "Missing Letters",
      desc: "Find the hidden letter",
      iconName: "Search",
      path: "/test/english_missing_letters",
      subject: "English",
    },
    {
      id: "english_spelling",
      title: "Listen and Find",
      desc: "Tap the word you hear",
      iconName: "Gamepad2",
      path: "/test/english_spelling",
      subject: "English",
    },
    {
      id: "spelling_test",
      title: "Spelling Hero",
      desc: "Mix of Spellings",
      iconName: "SpellCheck",
      path: "/test/spelling_test",
      subject: "English",
    },
    {
      id: "hindi_test",
      title: "Hindi Legend",
      desc: "Master the Varnamala",
      iconName: "Languages",
      path: "/test/hindi_test",
      subject: "Hindi",
    },
    {
      id: "telugu_test",
      title: "Telugu Legend",
      desc: "Master the Varnasala",
      iconName: "Languages",
      path: "/test/telugu_test",
      subject: "Telugu",
    },
    {
      id: "logic_test",
      title: "Grand Logic",
      desc: "Patterns & Puzzles",
      iconName: "Brain",
      path: "/test/logic_test",
      subject: "Logic",
    },
    {
      id: "master_test",
      title: "Grand Master",
      desc: "A mix of everything!",
      iconName: "Trophy",
      path: "/master_test",
      subject: "Logic",
    },
  ],
};
